# Stock Market Portfolio Optimisation - Utkarsh Gaikwad

### Read List of Nifty 50 stocks

In [40]:
import pandas as pd
A = pd.read_csv("D:/Nifty 50 index list/ind_nifty50list.csv")
A

,Company Name,Industry,Symbol,Series,ISIN Code
0,Adani Ports and Special Economic Zone Ltd.,Services,ADANIPORTS,EQ,INE742F01042
1,Apollo Hospitals Enterprise Ltd.,Healthcare,APOLLOHOSP,EQ,INE437A01024
2,Asian Paints Ltd.,Consumer Durables,ASIANPAINT,EQ,INE021A01026
3,Axis Bank Ltd.,Financial Services,AXISBANK,EQ,INE238A01034
4,Bajaj Auto Ltd.,Automobile and Auto Components,BAJAJ-AUTO,EQ,INE917I01010
5,Bajaj Finance Ltd.,Financial Services,BAJFINANCE,EQ,INE296A01024
6,Bajaj Finserv Ltd.,Financial Services,BAJAJFINSV,EQ,INE918I01018
7,Bharat Petroleum Corporation Ltd.,Oil Gas & Consumable Fuels,BPCL,EQ,INE029A01011
8,Bharti Airtel Ltd.,Telecommunication,BHARTIARTL,EQ,INE397D01024
9,Britannia Industries Ltd.,Fast Moving Consumer Goods,BRITANNIA,EQ,INE216A01030
10,Cipla Ltd.,Healthcare,CIPLA,EQ,INE059A01026
11,Coal India Ltd.,Oil Gas & Consumable Fuels,COALINDIA,EQ,INE522F01014
12,Divi's Laboratories Ltd.,Healthcare,DIVISLAB,EQ,INE361B01024
13,Dr. Reddy's Laboratories Ltd.,Healthcare,DRREDDY,EQ,INE089A01023
14,Eicher Motors Ltd.,Automobile and Auto Components,EICHERMOT,EQ,INE066A01021
15,Grasim Industries Ltd.,Construction Materials,GRASIM,EQ,INE047A01021
16,HCL Technologies Ltd.,Information Technology,HCLTECH,EQ,INE860A01027
17,HDFC Bank Ltd.,Financial Services,HDFCBANK,EQ,INE040A01034
18,HDFC Life Insurance Company Ltd.,Financial Services,HDFCLIFE,EQ,INE795G01014
19,Hero MotoCorp Ltd.,Automobile and Auto Components,HEROMOTOCO,EQ,INE158A01026
20,Hindalco Industries Ltd.,Metals & Mining,HINDALCO,EQ,INE038A01020
21,Hindustan Unilever Ltd.,Fast Moving Consumer Goods,HINDUNILVR,EQ,INE030A01027
22,Housing Development Finance Corporation Ltd.,Financial Services,HDFC,EQ,INE001A01036
23,ICICI Bank Ltd.,Financial Services,ICICIBANK,EQ,INE090A01021
24,ITC Ltd.,Fast Moving Consumer Goods,ITC,EQ,INE154A01025
25,IndusInd Bank Ltd.,Financial Services,INDUSINDBK,EQ,INE095A01012
26,Infosys Ltd.,Information Technology,INFY,EQ,INE009A01021
27,JSW Steel Ltd.,Metals & Mining,JSWSTEEL,EQ,INE019A01038
28,Kotak Mahindra Bank Ltd.,Financial Services,KOTAKBANK,EQ,INE237A01028
29,Larsen & Toubro Ltd.,Construction,LT,EQ,INE018A01030
30,Mahindra & Mahindra Ltd.,Automobile and Auto Components,M&M,EQ,INE101A01026
31,Maruti Suzuki India Ltd.,Automobile and Auto Components,MARUTI,EQ,INE585B01010
32,NTPC Ltd.,Power,NTPC,EQ,INE733E01010
33,Nestle India Ltd.,Fast Moving Consumer Goods,NESTLEIND,EQ,INE239A01016
34,Oil & Natural Gas Corporation Ltd.,Oil Gas & Consumable Fuels,ONGC,EQ,INE213A01029
35,Power Grid Corporation of India Ltd.,Power,POWERGRID,EQ,INE752E01010
36,Reliance Industries Ltd.,Oil Gas & Consumable Fuels,RELIANCE,EQ,INE002A01018
37,SBI Life Insurance Company Ltd.,Financial Services,SBILIFE,EQ,INE123W01016
38,Shree Cement Ltd.,Construction Materials,SHREECEM,EQ,INE070A01015
39,State Bank of India,Financial Services,SBIN,EQ,INE062A01020
40,Sun Pharmaceutical Industries Ltd.,Healthcare,SUNPHARMA,EQ,INE044A01036
41,Tata Consultancy Services Ltd.,Information Technology,TCS,EQ,INE467B01029
42,Tata Consumer Products Ltd.,Fast Moving Consumer Goods,TATACONSUM,EQ,INE192A01025
43,Tata Motors Ltd.,Automobile and Auto Components,TATAMOTORS,EQ,INE155A01022
44,Tata Steel Ltd.,Metals & Mining,TATASTEEL,EQ,INE081A01012
45,Tech Mahindra Ltd.,Information Technology,TECHM,EQ,INE669C01036
46,Titan Company Ltd.,Consumer Durables,TITAN,EQ,INE280A01028
47,UPL Ltd.,Chemicals,UPL,EQ,INE628A01036
48,UltraTech Cement Ltd.,Construction Materials,ULTRACEMCO,EQ,INE481G01011
49,Wipro Ltd.,Information Technology,WIPRO,EQ,INE075A01022

In [41]:
A['yfinance ticker'] = A['Symbol']+'.NS'

In [42]:
tickers = list(A['yfinance ticker'])

In [43]:
import yfinance as yf
d = yf.download(tickers,period='ytd',interval='1d')
d.head()

[*********************100%***********************]  50 of 50 completed

               Adj Close                                          \
           ADANIPORTS.NS APOLLOHOSP.NS ASIANPAINT.NS AXISBANK.NS
Date
2022-01-03    731.532227   4976.881348   3402.790527  695.291626
2022-01-04    734.164001   4951.052246   3439.479248  708.072205
2022-01-05    749.706360   4959.678711   3506.592529  725.795227
2022-01-06    734.710205   4950.902832   3494.511963  729.190063
2022-01-07    731.035645   5008.145996   3555.808838  729.489563

                                                                    \
           BAJAJ-AUTO.NS BAJAJFINSV.NS BAJFINANCE.NS BHARTIARTL.NS
Date
2022-01-03   3158.473633  16975.185547   7193.408203    688.240906
2022-01-04   3170.087158  17129.279297   7316.360352    694.363708
2022-01-05   3236.975098  17981.923828   7642.970703    696.902405
2022-01-06   3294.465820  17980.023438   7720.140137    707.256409
2022-01-07   3269.696289  17750.505859   7631.562988    701.581665

                                     ...       Volume                \
               BPCL.NS BRITANNIA.NS  ... SUNPHARMA.NS TATACONSUM.NS
Date                                 ...
2022-01-03  374.373993  3501.350586  ...      3726756        925699
2022-01-04  374.228516  3521.578857  ...      3027262       2352482
2022-01-05  382.712769  3542.146240  ...      2436343       2076552
2022-01-06  383.779358  3557.051758  ...      2423850       2077754
2022-01-07  384.167236  3617.302246  ...      1475374       2107056

                                                                  \
           TATAMOTORS.NS TATASTEEL.NS   TCS.NS TECHM.NS TITAN.NS
Date
2022-01-03      32748423     38658030  2346158  1779147   921729
2022-01-04      24100985     59757310  2488606  2701533  1037293
2022-01-05      15420105     61861760  1733031  3138050  1244568
2022-01-06      16563230     53354000  1810293  4290750  1130508
2022-01-07      15532165     39738570  2460591  2103362  4625230


           ULTRACEMCO.NS   UPL.NS WIPRO.NS
Date
2022-01-03        250533  1157591  4640405
2022-01-04        315188  1247395  5114400
2022-01-05        400874  1156604  7355632
2022-01-06        403448  5436867  6441610
2022-01-07        543512  2052552  6560163

[5 rows x 300 columns]

In [44]:
df= d['Adj Close']
df.head()

,ADANIPORTS.NS,APOLLOHOSP.NS,ASIANPAINT.NS,AXISBANK.NS,BAJAJ-AUTO.NS,BAJAJFINSV.NS,BAJFINANCE.NS,BHARTIARTL.NS,BPCL.NS,BRITANNIA.NS,...,SUNPHARMA.NS,TATACONSUM.NS,TATAMOTORS.NS,TATASTEEL.NS,TCS.NS,TECHM.NS,TITAN.NS,ULTRACEMCO.NS,UPL.NS,WIPRO.NS
Date,,,,,,,,,,,,,,,,,,,,,
2022-01-03,731.532227,4976.881348,3402.790527,695.291626,3158.473633,16975.185547,7193.408203,688.240906,374.373993,3501.350586,...,839.547119,742.023132,497.600006,50.783611,3775.587402,1759.193115,2514.952881,7679.813965,753.678894,711.607666
2022-01-04,734.164001,4951.052246,3439.479248,708.072205,3170.087158,17129.279297,7316.360352,694.363708,374.228516,3521.578857,...,828.421692,732.946228,489.600006,51.065880,3841.847412,1764.121460,2573.894287,7606.684082,751.262634,714.380005
2022-01-05,749.706360,4959.678711,3506.592529,725.795227,3236.975098,17981.923828,7642.970703,696.902405,382.712769,3542.146240,...,825.850464,727.738159,489.750000,52.346085,3818.310547,1712.621094,2567.068359,7615.831055,753.974731,706.458923
2022-01-06,734.710205,4950.902832,3494.511963,729.190063,3294.465820,17980.023438,7720.140137,707.256409,383.779358,3557.051758,...,820.411377,719.653320,488.850006,51.708202,3765.401123,1667.823120,2586.748779,7415.978516,771.973511,698.785461
2022-01-07,731.035645,5008.145996,3555.808838,729.489563,3269.696289,17750.505859,7631.562988,701.581665,384.167236,3617.302246,...,819.768677,730.218201,490.600006,51.579296,3810.942627,1679.404541,2563.630615,7514.811523,778.088135,704.478699

### Import Python Portfolio Optimisation Library

In [45]:
from pypfopt.efficient_frontier import EfficientFrontier
from pypfopt import risk_models
from pypfopt import expected_returns

In [46]:
mu = expected_returns.mean_historical_return(df)
s = risk_models.sample_cov(df)

In [47]:
ef = EfficientFrontier(mu,s)
weights = ef.max_sharpe()
cleaned_weights = ef.clean_weights()
print(cleaned_weights)
ef.portfolio_performance(verbose=True)

OrderedDict([('ADANIPORTS.NS', 0.0), ('APOLLOHOSP.NS', 0.0), ('ASIANPAINT.NS', 0.0), ('AXISBANK.NS', 0.0), ('BAJAJ-AUTO.NS', 0.05656), ('BAJAJFINSV.NS', 0.0), ('BAJFINANCE.NS', 0.0), ('BHARTIARTL.NS', 0.0), ('BPCL.NS', 0.0), ('BRITANNIA.NS', 0.0), ('CIPLA.NS', 0.0), ('COALINDIA.NS', 0.07508), ('DIVISLAB.NS', 0.0), ('DRREDDY.NS', 0.0), ('EICHERMOT.NS', 0.0), ('GRASIM.NS', 0.0), ('HCLTECH.NS', 0.0), ('HDFC.NS', 0.0), ('HDFCBANK.NS', 0.0), ('HDFCLIFE.NS', 0.0), ('HEROMOTOCO.NS', 0.0), ('HINDALCO.NS', 0.0), ('HINDUNILVR.NS', 0.0), ('ICICIBANK.NS', 0.0), ('INDUSINDBK.NS', 0.0), ('INFY.NS', 0.0), ('ITC.NS', 0.57566), ('JSWSTEEL.NS', 0.0), ('KOTAKBANK.NS', 0.0), ('LT.NS', 0.0), ('M&M.NS', 0.24868), ('MARUTI.NS', 0.0), ('NESTLEIND.NS', 0.0), ('NTPC.NS', 0.0), ('ONGC.NS', 0.0), ('POWERGRID.NS', 0.0), ('RELIANCE.NS', 0.0), ('SBILIFE.NS', 0.0), ('SBIN.NS', 0.0), ('SHREECEM.NS', 0.0), ('SUNPHARMA.NS', 0.0), ('TATACONSUM.NS', 0.0), ('TATAMOTORS.NS', 0.0), ('TATASTEEL.NS', 0.04401), ('TCS.NS', 0.0), ('TECHM.NS', 0.0), ('TITAN.NS', 0.0), ('ULTRACEMCO.NS', 0.0), ('UPL.NS', 0.0), ('WIPRO.NS', 0.0)])
Expected annual return: 93.9%
Annual volatility: 19.3%
Sharpe Ratio: 4.75

(0.9386714196123247, 0.19343943728494728, 4.749142328505999)

### Allocate shares for value of 10000 INR

In [48]:
from pypfopt.discrete_allocation import DiscreteAllocation, get_latest_prices

portfolio_val = 10000
latest_prices = get_latest_prices(df)
weights = cleaned_weights
da = DiscreteAllocation(weights, latest_prices,total_portfolio_value=portfolio_val)
allocation, leftover = da.lp_portfolio()
print('Discrete Allocation : ',allocation)
print('Funds Remaining     : ',round(leftover,2),'INR')

Discrete Allocation :  {'COALINDIA.NS': 4, 'ITC.NS': 19, 'M&M.NS': 2, 'TATASTEEL.NS': 5}
Funds Remaining     :  115.2 INR

In [49]:
import pandas as pd
al_key = allocation.keys()
al_values = allocation.values()
dfa = pd.DataFrame([al_key,al_values]).T
dfa.columns = ['yfinance ticker','Discrete Quantity']

In [50]:
dfa

  yfinance ticker Discrete Quantity
0    COALINDIA.NS                 4
1          ITC.NS                19
2          M&M.NS                 2
3    TATASTEEL.NS                 5

## Show how much Stocks to invest in which company

In [51]:
inner_join = pd.merge(A, 
                      dfa, 
                      on ='yfinance ticker', 
                      how ='inner')

In [52]:
inner_join.sort_values(by='Discrete Quantity',ascending=False)

,Company Name,Industry,Symbol,Series,ISIN Code,yfinance ticker,Discrete Quantity
1,ITC Ltd.,Fast Moving Consumer Goods,ITC,EQ,INE154A01025,ITC.NS,19
3,Tata Steel Ltd.,Metals & Mining,TATASTEEL,EQ,INE081A01012,TATASTEEL.NS,5
0,Coal India Ltd.,Oil Gas & Consumable Fuels,COALINDIA,EQ,INE522F01014,COALINDIA.NS,4
2,Mahindra & Mahindra Ltd.,Automobile and Auto Components,M&M,EQ,INE101A01026,M&M.NS,2